{ ==========================================
  選股策略：天外飛仙 (龍魂戰略總部第 6 掣 - 10日雙梯隊分流版)
  
  【 雙梯隊顯示與自動排序機制 】
  - 1-3 日 (黃金起爆期)：BASE_SCORE = 100 分 -> 自動優先排在畫面最頂部
  - 4-10 日 (延伸觀察期 7 天)：BASE_SCORE = 0 分 -> 自動沉底顯示在最底部
  - 11 日起：自動完全下架隱藏

  【 3 大 mandatory 基礎硬條件 】
  1. STAGE2 內 MACD 正式亮起「水上橙柱」(DIF>0 AND DEA>0 AND MACD>=0)
  2. STAGE2 內 TTM 向上亮金橙柱 (雙重確認)
  3. GRANDPA POWER 宏觀動能 > 0.5
  
  【 21 大非必要加分引擎 (純 Data 輸出) 】
========================================== }

{ --- 共用均線定義 --- }
MA10 := MA(CLOSE, 10);
MA20 := MA(CLOSE, 20);
MA50 := MA(CLOSE, 50);
MA150 := MA(CLOSE, 150);
MA200 := MA(CLOSE, 200);

{ ========================================== }
{ 基礎 STAGE 2 結構定義 }
{ ========================================== }
STAGE2 := CLOSE > MA50 AND CLOSE > MA150 AND MA50 > MA150 AND MA150 > MA200 AND MA200 > REF(MA200, 20) AND CLOSE > (LLV(LOW, 250) * 1.3);

{ ========================================== }
{ 硬條件 1: MACD 水上橙柱計時器 }
{ ========================================== }
DIF := EMA(CLOSE, 12) - EMA(CLOSE, 26);
DEA := EMA(DIF, 9);
MACD_VAL := (DIF - DEA) * 2;

STAGE2_WATER_ORANGE := STAGE2 AND MACD_VAL >= 0 AND DIF > 0 AND DEA > 0;
MACD_ORANGE_START := STAGE2_WATER_ORANGE AND NOT(REF(STAGE2_WATER_ORANGE, 1));
DAYS_SINCE_MACD_ORANGE := BARSLAST(MACD_ORANGE_START);

{ ========================================== }
{ 硬條件 2: GRANDPA POWER 宏觀動能 > 0.5 }
{ ========================================== }
RS := 2 * C / MA(C, 63) + C / MA(C, 126) + C / MA(C, 189) + C / MA(C, 252);
POWER := RS - 5;
POWER_STRONG := POWER > 0.5;

{ ========================================== }
{ 硬條件 3: TTM 橙柱雙確認 }
{ ========================================== }
N_TTM := 20;
VAR1 := (HHV(HIGH, N_TTM) + LLV(LOW, N_TTM)) / 2 + MA(CLOSE, N_TTM);
VAR2 := FORCAST(CLOSE - VAR1 / 2, N_TTM);
TTM_PRICE_HOLD := COUNT(CLOSE > MA150, 3) > 0;
TTM_STAGE2_ON := TTM_PRICE_HOLD AND (MA50 > MA150) AND (MA150 > REF(MA150, 10));
IS_ORANGE_UP := VAR2 >= 0 AND TTM_STAGE2_ON AND VAR2 > REF(VAR2, 1);
DAYS_SINCE_NOT_ORANGE := BARSLAST(NOT(IS_ORANGE_UP));
NEW_ORANGE_AFTER_CROSS := IS_ORANGE_UP AND (DAYS_SINCE_NOT_ORANGE <= DAYS_SINCE_MACD_ORANGE + 1);
HAS_ORANGE_IN_STAGE2 := NEW_ORANGE_AFTER_CROSS AND STAGE2;

{ ========================================== }
{ 雙梯隊時間窗口判斷 }
{ ========================================== }
RAW_BASE_MATCH := STAGE2_WATER_ORANGE AND POWER_STRONG AND HAS_ORANGE_IN_STAGE2;
IS_HOT_WINDOW := RAW_BASE_MATCH AND DAYS_SINCE_MACD_ORANGE <= 2;
IS_COOL_WINDOW := STAGE2 AND (DAYS_SINCE_MACD_ORANGE >= 3 AND DAYS_SINCE_MACD_ORANGE <= 9) AND COUNT(RAW_BASE_MATCH, 10) > 0;
BASE_MATCH := IS_HOT_WINDOW OR IS_COOL_WINDOW;
BASE_RANK_SCORE := IF(IS_HOT_WINDOW, 100, IF(IS_COOL_WINDOW, 0, -9999));
STATUS_FLAG := IF(IS_HOT_WINDOW, 1, IF(IS_COOL_WINDOW, 2, 0));

{ ========================================== }
{ 加分項 1-20 (保留原有 20 大引擎邏輯) }
{ ========================================== }
VOL_MA20 := MA(VOL, 20);
DAY_AMP := (HIGH - LOW) / REF(CLOSE, 1) * 100;
AMP_SQUEEZE := DAY_AMP < (MA(DAY_AMP, 20) * 0.75);
VOL_SQUEEZE := VOL < (VOL_MA20 * 0.75);
ATR20 := MA(TR, 20);
BOLLING_BAND := MA20 + 2 * STD(CLOSE, 20);
KELTNER_BAND := MA20 + 1.5 * ATR20;
TTM_SQUEEZE  := BOLLING_BAND < KELTNER_BAND;
WAS_SQUEEZED := COUNT(AMP_SQUEEZE AND VOL_SQUEEZE AND TTM_SQUEEZE, 5) >= 1;
TF_BUY_SP  := CLOSE - LOW;
TF_SELL_SP := HIGH - CLOSE;
INNER_POWER := (TF_BUY_SP > TF_SELL_SP) OR ((CLOSE - LOW) / (HIGH - LOW) > 0.60);
STOCK_DELTA := CLOSE - REF(CLOSE, 1);
DELTA_ACC   := STOCK_DELTA - REF(STOCK_DELTA, 1);
DELTA_POWER := DELTA_ACC > 0 AND CLOSE > OPEN;
BETA_OK := (MA(TR, 14) / MA20) * 100 > 1.2;
SPRING_READY := STAGE2 AND WAS_SQUEEZED AND BETA_OK;
SPRING_SIGNAL := SPRING_READY AND INNER_POWER AND DELTA_POWER;
CNT_SPRING := IF(BASE_MATCH, COUNT(SPRING_SIGNAL AND NOT(REF(SPRING_SIGNAL, 1)), 5), 0);

MA200向上 := MA200 > REF(MA200, 20);
VCP_STAGE2 := C >= MA50 AND (MA50 > MA150 AND MA150 > MA200) AND MA200向上;
波幅大 := (HHV(H, 30) - LLV(L, 30)) / LLV(L, 30) * 100;
波幅窄 := (HHV(H, 8) - LLV(L, 8)) / LLV(L, 8) * 100;
VCP預備 := 波幅窄 <= (波幅大 * 0.65) AND 波幅窄 <= 10;
飆升動能 := (C / REF(LLV(L, 40), 10)) > 1.9;
旗部波幅 := (HHV(H, 12) - LLV(L, 12)) / LLV(L, 12) * 100;
HTF預備 := VCP_STAGE2 AND 飆升動能 AND 旗部波幅 < 20;
MAV20 := MA(V, 20);
近期高位 := REF(HHV(H, 10), 1);
突破 := CROSS(C, 近期高位) AND V > (MAV20 * 1.3);
IS_VCP := 突破 AND REF(VCP預備, 1);
IS_HTF := 突破 AND REF(HTF預備, 1);
IS_BOTH := IS_VCP AND IS_HTF;
ONLY_VCP := IS_VCP AND NOT(IS_BOTH);
ONLY_HTF := IS_HTF AND NOT(IS_BOTH);
聚氣中 := HTF預備 OR VCP預備;
近期有聚氣 := COUNT(聚氣中, 5) >= 1;
爆發大陽 := (C / REF(C, 1)) > 1.04;
真破頂 := (C > 近期高位) AND 爆發大陽;
漏網神龍 := 真破頂 AND 近期有聚氣 AND NOT(突破);
極端記憶 := COUNT(聚氣中, 15) >= 1;
創15日新高 := C > REF(HHV(H, 15), 1);
IS_SNDK := 創15日新高 AND 極端記憶 AND NOT(突破) AND NOT(漏網神龍);
曾經聚氣 := COUNT(聚氣中, 15) >= 1;
創20日高 := C > REF(HHV(H, 20), 1);
單日暴升 := (C / REF(C, 1)) > 1.05;
IS_ULTIMATE := VCP_STAGE2 AND 曾經聚氣 AND 創20日高 AND 單日暴升 AND NOT(突破);
狂暴趨勢 := C > MA(C, 20) AND MA(C, 20) > MA(C, 50);
近期暴升 := (C / REF(LLV(L, 30), 5)) > 1.5;
今日強勢破頂 := (C > REF(HHV(H, 10), 1)) AND (C > O) AND ((C / REF(C, 1)) > 1.03);
IS_PARABOLIC := 狂暴趨勢 AND 近期暴升 AND 今日強勢破頂 AND NOT(突破) AND NOT(IS_ULTIMATE) AND NOT(IS_SNDK) AND NOT(漏網神龍);
N_大陽條件 := (C / REF(C, 1) >= 1.04) AND (C > O);
N_前次大陽天數 := REF(BARSLAST(N_大陽條件), 1) + 1;
N_目標高位 := REF(H, N_前次大陽天數);
N_突破 := (N_前次大陽天數 <= 20) AND (C > N_目標高位) AND (REF(C, 1) <= N_目標高位) AND (C > O);
ALL_PREV_SIGNALS := ONLY_VCP OR ONLY_HTF OR IS_BOTH OR 漏網神龍 OR IS_SNDK OR IS_ULTIMATE OR IS_PARABOLIC;
IS_N_SHAPE := VCP_STAGE2 AND N_突破 AND NOT(ALL_PREV_SIGNALS);
大趨勢多頭 := MA50 > MA150 AND MA150 > MA200 AND MA200向上;
短線洗盤 := COUNT(MA10 < MA20, 3) >= 1;
短線前夕 := MA10 <= MA20 AND (MA10 + (MA10 - REF(MA10,1))) > (MA20 + (MA20 - REF(MA20,1))) AND C > O;
中線洗盤 := COUNT(MA20 < MA50, 5) >= 1;
中線前夕 := MA20 <= MA50 AND (MA20 + (MA20 - REF(MA20,1))) > (MA50 + (MA50 - REF(MA50,1))) AND C > O;
IS_AMBUSH := 大趨勢多頭 AND ((短線洗盤 AND 短線前夕) OR (中線洗盤 AND 中線前夕)) AND NOT(ALL_PREV_SIGNALS) AND NOT(IS_N_SHAPE);
大資金流入 := (V >= (MAV20 * 1.5)) AND (C > O);
ANY_BUY_SIGNAL := ALL_PREV_SIGNALS OR IS_N_SHAPE OR IS_AMBUSH;
SHOW_BIG_MONEY := ANY_BUY_SIGNAL AND 大資金流入;
CNT_MONEY_BAG := IF(BASE_MATCH, COUNT(SHOW_BIG_MONEY, 5), 0);

LC := REF(CLOSE, 1);
RSI_VAL := SMA(MAX(CLOSE - LC, 0), 14, 1) / SMA(ABS(CLOSE - LC), 14, 1) * 100;
RSI_STAGE2_50 := STAGE2 AND (RSI_VAL > 50);
CNT_RSI := IF(BASE_MATCH AND RSI_STAGE2_50, 1, 0);

TYP_V := (HIGH + LOW + CLOSE) / 3;
VOL1_V := SUM(IF(TYP_V > REF(TYP_V, 1), TYP_V * VOL, 0), 14);
VOL2_V := SUM(IF(TYP_V < REF(TYP_V, 1), TYP_V * VOL, 0), 14);
MFI_V := 100 * VOL1_V / (VOL1_V + VOL2_V + 0.00001);
OBV_RAW_RAW := SUM(IF(CLOSE > REF(CLOSE, 1), VOL, IF(CLOSE < REF(CLOSE, 1), -VOL, 0)), 120);
OBV_RAW := EMA(OBV_RAW_RAW, 3);
MAX_OBV := HHV(OBV_RAW, 120);
MIN_OBV := LLV(OBV_RAW, 120);
OBV_NORM := (OBV_RAW - MIN_OBV) / (MAX_OBV - MIN_OBV + 0.00001) * 100;
OBV_SIGNAL := MA(OBV_NORM, 20);
SMART_BUY := CROSS(OBV_NORM, OBV_SIGNAL) AND MFI_V > 40;
SMART_BUY_FILTER := FILTER(SMART_BUY, 12);
CNT_SWEEP := IF(BASE_MATCH, COUNT(SMART_BUY_FILTER, 7), 0);

VA_OBV := IF(CLOSE > REF(CLOSE, 1), VOL, IF(CLOSE < REF(CLOSE, 1), -VOL, 0));
OBV_LINE := SUM(VA_OBV, 250); 
OBV_HHV := REF(HHV(OBV_LINE, 30), 1);
OBV_BREAK := CROSS(OBV_LINE, OBV_HHV) AND STAGE2; 
PRICE_NOT_HIGH := CLOSE < HHV(CLOSE, 10);
SMART_ACC := OBV_BREAK AND PRICE_NOT_HIGH;
FUND_BREAK := OBV_BREAK AND NOT(SMART_ACC);
CNT_SMART_ACC := IF(BASE_MATCH, COUNT(SMART_ACC, 6), 0);
CNT_FUND_BREAK := IF(BASE_MATCH, COUNT(FUND_BREAK, 6), 0);

N_PERIOD := 50;
TYP_PRICE := (HIGH + LOW + CLOSE) / 3;
TOTAL_VOL := SUM(VOL, N_PERIOD);
TOTAL_VAL := SUM(TYP_PRICE * VOL, N_PERIOD);
POC_LINE := IF(TOTAL_VOL > 0, TOTAL_VAL / TOTAL_VOL, CLOSE);
VOL_VAR := SUM(VOL * (TYP_PRICE - POC_LINE) * (TYP_PRICE - POC_LINE), N_PERIOD) / (TOTAL_VOL + 0.00001);
VOL_STD := IF(TOTAL_VOL > 0, SQRT(VOL_VAR), 0);
VAH_LINE := POC_LINE + (1.0 * VOL_STD);
BULL_BREAK := STAGE2 AND CROSS(CLOSE, VAH_LINE) AND VOL > MA(VOL, 5);
CNT_BULL_BREAK := IF(BASE_MATCH, COUNT(BULL_BREAK, 6), 0);

VOLMA20_BIG := MA(VOL, 20);
CSPRE := ABS(CLOSE - OPEN);
AVGS := MA(CSPRE, 20);
ISBIG := (VOL > VOLMA20_BIG * 1.5) AND (CLOSE > OPEN) AND (CSPRE > AVGS);
CNT_BIG := IF(BASE_MATCH, COUNT(ISBIG, 3), 0);

S_EMA20 := EMA(CLOSE, 20);
S_EMA50 := EMA(CLOSE, 50);
S_EMA200 := EMA(CLOSE, 200);
S_E5 := EMA(CLOSE, 5);
S_E10 := EMA(CLOSE, 10);
S_VMA5 := MA(VOL, 5);
S_INST_VOL := VOL > (S_VMA5 * 1.2);
S_BODY_RANGE := HIGH - LOW;
S_STRONG_BUY_K := (CLOSE > OPEN) AND ((CLOSE - LOW) > S_BODY_RANGE * 0.50);
S_CROSS_BUY := CROSS(CLOSE, S_EMA20) OR (CLOSE > S_EMA20 AND CROSS(S_E5, S_E10));
S_PULLBACK_BUY := (LOW <= S_EMA20) AND (CLOSE > S_EMA20) AND (CLOSE > OPEN);
SP_BUY_SIGNAL := STAGE2 AND S_INST_VOL AND S_STRONG_BUY_K AND (S_CROSS_BUY OR S_PULLBACK_BUY);
CNT_SPLUS := IF(BASE_MATCH, COUNT(SP_BUY_SIGNAL, 3), 0);

MAVOL20_HUGE := MA(VOL, 20);
IS_HUGE_VOL := VOL > (MAVOL20_HUGE * 2.0);
IS_UP_CANDLE := CLOSE >= OPEN;
HUGE_VOL_SIGNAL := IS_HUGE_VOL AND IS_UP_CANDLE;
CNT_HUGE_VOL := IF(BASE_MATCH, COUNT(HUGE_VOL_SIGNAL, 4), 0);

DMI_N := 14;
DMI_M := 6;
DMI_TR1 := SUM(MAX(MAX(HIGH-LOW,ABS(HIGH-REF(CLOSE,1))),ABS(LOW-REF(CLOSE,1))),DMI_N);
DMI_HD := HIGH-REF(HIGH,1);
DMI_LD := REF(LOW,1)-LOW;
DMI_DMP := SUM(IF(DMI_HD>0 AND DMI_HD>DMI_LD,DMI_HD,0),DMI_N);
DMI_DMM := SUM(IF(DMI_LD>0 AND DMI_LD>DMI_HD,DMI_LD,0),DMI_N);
DMI_PDI := DMI_DMP*100/DMI_TR1;
DMI_MDI := DMI_DMM*100/DMI_TR1;
DMI_ADX_RAW := MA(ABS(DMI_MDI-DMI_PDI)/(DMI_MDI+DMI_PDI)*100,DMI_M);
DMI_BULL_DOMINANT := DMI_PDI > DMI_MDI;
DMI_TREND_ACTIVE := DMI_ADX_RAW >= 25;
DMI_BULL_GAP := DMI_PDI - DMI_MDI > 3;
DMI_BULL_CROSS := CROSS(DMI_ADX_RAW, 25) AND DMI_BULL_DOMINANT AND DMI_BULL_GAP;
DMI_BULL_FLIP := CROSS(DMI_PDI, DMI_MDI) AND DMI_TREND_ACTIVE AND DMI_BULL_GAP;
DMI_TREND_IGNITE := (DMI_BULL_CROSS OR DMI_BULL_FLIP) AND STAGE2;
DMI_SQUEEZE_SIGNAL := CROSS(15, DMI_ADX_RAW);
CNT_TORNADO := IF(BASE_MATCH, COUNT(DMI_TREND_IGNITE, 4), 0);
CNT_NINJA := IF(BASE_MATCH, COUNT(DMI_SQUEEZE_SIGNAL, 4), 0);

PZ_N:=24; PZ_M:=2.5; PZ_V_LEN:=13; PZ_ATR_LEN:=20;
PZ_MID_V := MA(CLOSE, PZ_N);
PZ_STD_DEV_V := STD(CLOSE, PZ_N);
PZ_UPPER_V := PZ_MID_V + PZ_M * PZ_STD_DEV_V;
PZ_LOWER_V := PZ_MID_V - PZ_M * PZ_STD_DEV_V;
PZ_TR_V := MAX(MAX(HIGH-LOW, ABS(HIGH-REF(CLOSE,1))), ABS(LOW-REF(CLOSE,1)));
PZ_ATR_V := MA(PZ_TR_V, PZ_ATR_LEN);
PZ_EXTREME_MARKET := PZ_TR_V > PZ_ATR_V * 2;
PZ_IS_RANGE := ((PZ_UPPER_V - PZ_LOWER_V) / PZ_MID_V * 100) < MA((PZ_UPPER_V - PZ_LOWER_V) / PZ_MID_V * 100, 50);
PZ_VOL_FORCE := (CLOSE - PZ_MID_V) / PZ_STD_DEV_V * 100;
PZ_E1 := EMA(PZ_VOL_FORCE, PZ_V_LEN);
PZ_E2 := EMA(PZ_E1, PZ_V_LEN);
PZ_V_SIGNAL := 2 * PZ_E1 - PZ_E2;
PZ_VOL_OK := VOL > MA(VOL, 20);
PZ_BUY1 := CROSS(CLOSE, PZ_UPPER_V) AND PZ_V_SIGNAL > 50 AND PZ_VOL_OK AND PZ_IS_RANGE;
PZ_BUY2 := PZ_V_SIGNAL > 50 AND CLOSE > MA(CLOSE, 10) AND CLOSE > REF(CLOSE, 1) AND STAGE2 AND NOT(PZ_EXTREME_MARKET);
PZ_BUY3 := CROSS(PZ_V_SIGNAL, 50) AND CLOSE > PZ_MID_V AND PZ_VOL_OK;
PZ_BUY1_FILTERED := PZ_BUY1;
PZ_BUY3_FILTERED := PZ_BUY3 AND NOT(PZ_BUY1);
PZ_BUY2_FILTERED := FILTER(PZ_BUY2, 8);
PZ_ANY_BUY := PZ_BUY1_FILTERED OR PZ_BUY3_FILTERED OR PZ_BUY2_FILTERED;
CNT_PZ_ANY := IF(BASE_MATCH, COUNT(PZ_ANY_BUY, 4), 0);
SHOW_PZ1 := IF(BASE_MATCH AND COUNT(PZ_BUY1_FILTERED, 4) > 0, 1, 0);
SHOW_PZ3 := IF(BASE_MATCH AND COUNT(PZ_BUY3_FILTERED, 4) > 0, 1, 0);
SHOW_PZ2 := IF(BASE_MATCH AND COUNT(PZ_BUY2_FILTERED, 4) > 0, 1, 0);

GL_LC := REF(CLOSE, 1);
GL_RSI1 := SMA(MAX(CLOSE - GL_LC, 0), 14, 1) / (SMA(ABS(CLOSE - GL_LC), 14, 1) + 0.00001) * 100;
GL_TYP := (HIGH + LOW + CLOSE) / 3;
GL_V1 := SUM(IF(GL_TYP > REF(GL_TYP, 1), GL_TYP * VOL, 0), 14);
GL_V2 := SUM(IF(GL_TYP < REF(GL_TYP, 1), GL_TYP * VOL, 0), 14);
GL_MFI1 := 100 * GL_V1 / (GL_V1 + GL_V2 + 0.00001);
GL_TRUE_MOM := (GL_RSI1 + GL_MFI1) / 2 - 50;
GL_RV := GL_TRUE_MOM;
GL_SV := EMA(GL_TRUE_MOM, 9);
GL_HD := HIGH - REF(HIGH, 1);
GL_LD := REF(LOW, 1) - LOW;
GL_DMP := SUM(IF(GL_HD > 0 AND GL_HD > GL_LD, GL_HD, 0), 14);
GL_DMM := SUM(IF(GL_LD > 0 AND GL_LD > GL_HD, GL_LD, 0), 14);
GL_TR_A := SUM(MAX(MAX(HIGH - LOW, ABS(HIGH - REF(CLOSE, 1))), ABS(LOW - REF(CLOSE, 1))), 14);
GL_PDI := GL_DMP * 100 / (GL_TR_A + 0.00001);
GL_MDI := GL_DMM * 100 / (GL_TR_A + 0.00001);
GL_ADX := EXPMEMA(ABS(GL_MDI - GL_PDI) / (GL_MDI + GL_PDI + 0.00001) * 100, 14);
GL_IS_CHOPPY := GL_ADX < 20;
GL_PRO_BUY := CROSS(GL_RV, GL_SV) AND STAGE2 AND NOT(GL_IS_CHOPPY) AND GL_RV < 15;
CNT_GL_IGNITE := IF(BASE_MATCH, COUNT(GL_PRO_BUY, 4), 0);

WK_EMA20 := EMA(CLOSE, 20);
WK_EMA50 := EMA(CLOSE, 50);
WK_EMA200 := EMA(CLOSE, 200);
WK_IS_BEAR := CLOSE < WK_EMA200 OR WK_EMA50 < WK_EMA200;
WK_VMA5 := MA(VOL, 5);
WK_VMA20 := MA(VOL, 20);
WK_SPRING := CROSS(CLOSE, WK_EMA20) AND REF(CLOSE, 1) < WK_EMA20 AND (VOL > WK_VMA5 * 1.2 OR VOL < WK_VMA20 * 0.6) AND NOT(WK_IS_BEAR);
CNT_WK_SPRING := IF(BASE_MATCH, COUNT(WK_SPRING, 4), 0);

KO_TR_V := MAX(MAX(H-L, ABS(H-REF(C,1))), ABS(L-REF(C,1)));
KO_ATR14 := MA(KO_TR_V, 14);
KO_BASE_S := MAX(LLV(L, 30), C - (KO_ATR14 * 3.2));
KO_FINAL_S := IF(ISLASTBAR, KO_BASE_S, HHV(KO_BASE_S, 50));
KO_SAFE_ZONE := C > KO_FINAL_S AND C > MA(C, 15);
KO_VH_PRO := V > MA(V, 5) * 1.35 AND C > O;
KO_RED_TRIANGLE := KO_VH_PRO AND KO_SAFE_ZONE;
CNT_KO_RED_TRIANGLE := IF(BASE_MATCH, COUNT(KO_RED_TRIANGLE, 4), 0);

FLOW_VOL_MA50 := MA(VOL, 50);
FLOW_IS_VDU := (VOL < FLOW_VOL_MA50 * 0.5);
FLOW_IS_BREAKOUT := CLOSE >= HHV(REF(CLOSE, 1), 20);
FLOW_HIGH_VOL_BUY := (VOL > REF(VOL, 1)) AND (VOL > FLOW_VOL_MA50 * 1.5);
FLOW_INSTITUTION_BUY := STAGE2 AND (CLOSE > REF(CLOSE, 1)) AND FLOW_HIGH_VOL_BUY AND FLOW_IS_BREAKOUT;

FLOW_DIFF := EMA(CLOSE, 12) - EMA(CLOSE, 26);
FLOW_DEA  := EMA(FLOW_DIFF, 9);
FLOW_MACD_BAR := (FLOW_DIFF - FLOW_DEA) * 2;
FLOW_MACD_BAR_GROW := FLOW_MACD_BAR > REF(FLOW_MACD_BAR, 1) AND REF(FLOW_MACD_BAR, 1) > REF(FLOW_MACD_BAR, 2);
FLOW_MACD_POWER := FLOW_DIFF > FLOW_DEA AND FLOW_MACD_BAR > 0 AND FLOW_MACD_BAR_GROW;

FLOW_TTM_VAR1 := (HHV(HIGH, 20) + LLV(LOW, 20)) / 2 + MA(CLOSE, 20);
FLOW_TTM_VAR2 := FORCAST(CLOSE - FLOW_TTM_VAR1 / 2, 20);
FLOW_TTM_POWER := FLOW_TTM_VAR2 > REF(FLOW_TTM_VAR2, 1) AND FLOW_TTM_VAR2 >= 0;

FLOW_VDU_10D := COUNT(FLOW_IS_VDU, 10) > 0;
FLOW_COND_A := FLOW_VDU_10D AND FLOW_MACD_POWER;
FLOW_COND_B := FLOW_MACD_POWER AND FLOW_TTM_POWER;

FLOW_REAL_BUY := FLOW_INSTITUTION_BUY AND (FLOW_COND_A OR FLOW_COND_B);
CNT_FLOW_REAL_BUY := IF(BASE_MATCH, COUNT(FLOW_REAL_BUY, 4), 0);

NX_MA50  := MA(CLOSE, 50);
NX_MA150 := MA(CLOSE, 150);
NX_STAGE2 := COUNT(CLOSE > NX_MA150, 3) > 0 AND (NX_MA50 > NX_MA150) AND (NX_MA150 > REF(NX_MA150, 10));

NX_VOL_MA20 := MA(VOL, 20);
NX_COND_VOL := VOL > (NX_VOL_MA20 * 1.5);
NX_DAY_RANGE := HIGH - LOW;
NX_RANGE_MA20 := MA(NX_DAY_RANGE, 20);
NX_COND_RANGE := NX_DAY_RANGE > (NX_RANGE_MA20 * 1.5);
NX_RAW_SIGNAL := NX_COND_VOL AND NX_COND_RANGE;

NX_VOL_PAUSE := VOL < NX_VOL_MA20;
NX_VDU_READY := COUNT(NX_VOL_PAUSE, 10) > 0;

NX_TF_BUY := (CLOSE - LOW);
NX_TF_SELL := (HIGH - CLOSE);
NX_IS_YANG := CLOSE >= OPEN;
NX_POWER_OK := NX_TF_BUY > NX_TF_SELL;
NX_SURGE_UP := (HIGH - REF(CLOSE, 1)) / REF(CLOSE, 1) * 100 > 4.0;
NX_SAFE_LOCATION := (CLOSE - MA(CLOSE, 20)) / MA(CLOSE, 20) < 0.60;

NX_BUY_SAFE := NX_STAGE2 AND NX_VDU_READY AND NX_RAW_SIGNAL AND NX_IS_YANG AND NX_SURGE_UP AND NX_POWER_OK AND NX_SAFE_LOCATION;
CNT_NX_BUY_SAFE := IF(BASE_MATCH, COUNT(NX_BUY_SAFE, 3), 0);

VSA_VOL_MA20 := MA(VOL, 20);
VSA_C_SPREAD := ABS(CLOSE - OPEN);
VSA_AVG_SPREAD := MA(VSA_C_SPREAD, 20);
VSA_MA60_C := MA(CLOSE, 60);
VSA_DEV60 := (CLOSE - VSA_MA60_C) / VSA_MA60_C * 100;
VSA_IS_HIGH := VSA_DEV60 > 15;
VSA_IS_BIG_RAW := (VOL > VSA_VOL_MA20 * 1.5) AND (CLOSE > OPEN) AND (VSA_C_SPREAD > VSA_AVG_SPREAD);
VSA_START := VSA_IS_BIG_RAW AND NOT(VSA_IS_HIGH);
CNT_VSA_START := IF(BASE_MATCH, COUNT(VSA_START, 4), 0);

TF_V_MA := MA(VOL, 20);
TF_V_STD := STD(VOL, 20);
TF_V_UPPER := TF_V_MA + (2.0 * TF_V_STD);
TF_VOL_MA60 := MA(VOL, 60);
TF_AMP := ABS(CLOSE - REF(CLOSE, 1)) / REF(CLOSE, 1) * 100;
TF_MA60_C := MA(CLOSE, 60);
TF_DEV60 := (CLOSE - TF_MA60_C) / TF_MA60_C * 100;
TF_IS_HIGH := TF_DEV60 > 15;
TF_REAL_BOOM := (VOL > TF_V_UPPER) AND (VOL > TF_VOL_MA60 * 1.9) AND (TF_AMP > 2.0);
TF_FIRE := TF_REAL_BOOM AND (CLOSE > OPEN) AND NOT(TF_IS_HIGH);
CNT_TF_FIRE := IF(BASE_MATCH, COUNT(TF_FIRE, 4), 0);

SV19_E5 := EMA(CLOSE, 5);
SV19_E10 := EMA(CLOSE, 10);
SV19_E20 := EMA(CLOSE, 20);
SV19_E50 := EMA(CLOSE, 50);
SV19_E200 := EMA(CLOSE, 200);
SV19_STATE := IF(CLOSE > SV19_E20 AND SV19_E20 > SV19_E50 AND SV19_E50 > SV19_E200, 1, IF(CLOSE < SV19_E200 OR SV19_E50 < SV19_E200, 2, 3));
SV19_VMA5 := MA(VOL, 5);
SV19_INST_VOL := VOL > (SV19_VMA5 * 1.2);
SV19_BODY_RANGE := HIGH - LOW;
SV19_STRONG_K := (CLOSE > OPEN) AND ((CLOSE - LOW) > SV19_BODY_RANGE * 0.55);
SV19_TR1 := MAX(MAX(HIGH - LOW, ABS(HIGH - REF(CLOSE, 1))), ABS(LOW - REF(CLOSE, 1)));
SV19_ATR14 := MA(SV19_TR1, 14);
SV19_VOLATILITY_EXP := SV19_ATR14 > REF(SV19_ATR14, 1);
SV19_LC := REF(CLOSE, 1);
SV19_UP6 := SMA(MAX(CLOSE - SV19_LC, 0), 6, 1);
SV19_DN6 := SMA(ABS(CLOSE - SV19_LC), 6, 1);
SV19_MYRSI6 := SV19_UP6 / (SV19_DN6 + 0.00001) * 100;
SV19_NOT_EXHAUSTED := SV19_MYRSI6 < 78;
SV19_RAW_BUY := CROSS(SV19_E5, SV19_E10) AND SV19_INST_VOL AND SV19_STRONG_K AND SV19_VOLATILITY_EXP AND SV19_NOT_EXHAUSTED;
SV19_BUY_GREEN := SV19_RAW_BUY AND (SV19_STATE = 1);
CNT_S19_GREEN := IF(BASE_MATCH, COUNT(SV19_BUY_GREEN, 6), 0);

TFM_V1 := (CLOSE - LOW);
TFM_V2 := (HIGH - CLOSE);
TFM_V3 := (HIGH - LOW);
TFM_BUY := IF(TFM_V3 > 0, VOL * TFM_V1 / TFM_V3, 0);
TFM_SELL := IF(TFM_V3 > 0, VOL * TFM_V2 / TFM_V3, 0);
TFM_SUM_BUY := SUM(TFM_BUY, 5);
TFM_SUM_SELL := SUM(TFM_SELL, 5);
TFM_SUM_TOT := TFM_SUM_BUY + TFM_SUM_SELL;
TFM_WIN := (TFM_SUM_BUY / (TFM_SUM_TOT + 0.00001)) > 0.65;
CNT_TFM_WIN := IF(BASE_MATCH AND TFM_WIN, 1, 0);

{ ========================================== }
{ 加分項 21: CLIMAX (成交量高潮 - 突破60日高位且爆量2.5倍) }
{ 設定為當日及前 3 個交易日 (共 4 日) 內出現 }
{ ========================================== }
VCX_WR := (HHV(HIGH, 14) - CLOSE) / (HHV(HIGH, 14) - LLV(LOW, 14)) * -100;
VCX_VMA30 := MA(VOL, 30);
VCX_V_MAX60_V := VOL > REF(HHV(VOL, 60), 1);
VCX_CLIMAX := VCX_V_MAX60_V AND (VOL > VCX_VMA30 * 2.5) AND (HIGH >= REF(HHV(HIGH, 60), 1)) AND (VCX_WR > -10 OR ((HIGH - MAX(OPEN, CLOSE)) > ABS(CLOSE - OPEN) * 3 AND VCX_WR > -30));

CNT_CLIMAX := IF(BASE_MATCH, COUNT(VCX_CLIMAX, 4), 0);


{ ==========================================
  輸出變數 (精準對接 App 前端 UI 渲染)
========================================== }
天外飛仙 : STATUS_FLAG; { 1=黃金頂部, 2=沉底觀察, 0=隱藏 }

⚡爆邊(非💰) : CNT_SPRING;
💰錢袋 : CNT_MONEY_BAG;
動力rsi(非💰) : CNT_RSI;
💰掃貨 : CNT_SWEEP;
🕵️大戶吸籌 : CNT_SMART_ACC;
🌊資金突破 : CNT_FUND_BREAK;
🎯牛突破 : CNT_BULL_BREAK;
BIG : CNT_BIG;
🚀S+++突擊 : CNT_SPLUS;
🔥天量 : CNT_HUGE_VOL;
🌪️主升狂飆(非💰) : CNT_TORNADO;
🥷潛伏觀察(非💰) : CNT_NINJA;
PZ綜合訊號 : CNT_PZ_ANY;
🚀全能點火 : CNT_GL_IGNITE;
⚡洗盤 : CNT_WK_SPRING;
紅色三角 : CNT_KO_RED_TRIANGLE;
🔵真周線共振 : CNT_FLOW_REAL_BUY;
💎真動能 : CNT_NX_BUY_SAFE;
🚀啟動 : CNT_VSA_START;
🚀點火 : CNT_TF_FIRE;
🚀S級綠區主升 : CNT_S19_GREEN;
買入兵力大勝 : CNT_TFM_WIN;
CLIMAX : CNT_CLIMAX;

★PZ特大注★ : SHOW_PZ1;
🚀浴火重生 : SHOW_PZ3;
■PZ大注■ : SHOW_PZ2;

{ 霸王總分：含 100 分頂/底階梯權重，App 降序排列會自然將頭 3 天的股票排在最頂，第 4-10 天自動沉底 }
霸王總分 : BASE_RANK_SCORE + ⚡爆邊(非💰) + 💰錢袋 + 動力rsi(非💰) + 💰掃貨 + 🕵️大戶吸籌 + 🌊資金突破 + 🎯牛突破 + BIG + 🚀S+++突擊 + 🔥天量 + 🌪️主升狂飆(非💰) + 🥷潛伏觀察(非💰) + PZ綜合訊號 + 🚀全能點火 + ⚡洗盤 + 紅色三角 + 🔵真周線共振 + 💎真動能 + 🚀啟動 + 🚀點火 + 🚀S級綠區主升 + 買入兵力大勝 + CLIMAX;
